### ISSUE TITLE
Possiblity to change the fonts.

### ISSUE THREAD

**Issue by Amarok73** [nielsvaes/dcs_code_injector#10]
Hello,

Would it be possible to add the font selector for both panels?

**Comment by nielsvaes** [comment]
I'll look into it!

**Comment by Amarok73** [comment]
And another thing that comes to my mind, if the indentation could behave more like in regular code editors, so the next line would be indented to the same level as the previous one, then pressing the backspace at the beginning of the line would cause jump left to the previous indentation level. That would significantly improve the comfort, especially when writing plenty of code.
That's almost all my wishes I've since started working with this unbelievably useful tool.

**Comment by nielsvaes** [comment]
Selecting fonts for the Log view and Code views is added in v1.4.2 in the View menu.

**Comment by Amarok73** [comment]
Besides of some minor behavioral inconsistency it works pretty well and keeps the set fonts between the sessions. Thank You!
