### ISSUE TITLE
Better indentation handling

### ISSUE THREAD

**Issue by nielsvaes** [nielsvaes/dcs_code_injector#11]
And another thing that comes to my mind, if the indentation could behave more like in regular code editors, so the next line would be indented to the same level as the previous one, then pressing the backspace at the beginning of the line would cause jump left to the previous indentation level. That would significantly improve the comfort, especially when writing plenty of code.
That's almost all my wishes I've since started working with this unbelievably useful tool.

_Originally posted by @Amarok73 in https://github.com/nielsvaes/dcs_code_injector/issues/10#issuecomment-1923615994_

**Comment by Amarok73** [comment]
Works like a charm!
