### ISSUE TITLE
Optional activation for CodeInjector embedded LogViewer

### ISSUE THREAD

**Issue by Abburo** [nielsvaes/dcs_code_injector#15]
As Mission Designer I am often using MOOSE debugging option to help understand the errors generated by my scripts. This is leading to big "dcs.log" file size which seems to impact the way that code within Injector is transmitted to DCS.
Would be good if we can enable/disable the internal LogViewer so that CodeInjector might have an improved behavior for this scenarios.

**Comment by nielsvaes** [comment]
Has been added
