### ISSUE TITLE
www.virustotal.com lights your exe up like the sun

### ISSUE THREAD

**Issue by rbz518** [nielsvaes/dcs_code_injector#21]
@nielsvaes you might want to prioritize this one.
[TotalVirus.com](https://www.virustotal.com/gui/file/221d8783bfe2da6d825b1da2b5d79409ac260ab392d7139ee22c56720658cb72?nocache=1)

![image](https://github.com/user-attachments/assets/e0aec2bd-117e-4e20-ad3e-9937246f3563)

**Comment by nielsvaes** [comment]
https://github.com/nielsvaes/dcs_code_injector/issues/22
