### ISSUE TITLE
www.virustotal.com also appears to be full of jimmys

### ISSUE THREAD

**Issue by rbz518** [nielsvaes/dcs_code_injector#22]
My first upload was of a version I still had locally, this one is straight off your latest github downloads

[TotalVirus}(https://www.virustotal.com/gui/file/d814cc87402cb5554e179480c02951d650650151a9d6d7f936f3c34f982387a6?nocache=1)

![image](https://github.com/user-attachments/assets/cd3c7362-88ee-4447-a092-e342d0d3fe54)

**Comment by nielsvaes** [comment]
Yeah this happens because the .exe is basically just an embedded Python folder. There's no virus, you can see exactly how it gets built in the in the github actions file in the repo.
