### ISSUE TITLE
Reload MOOSE in the tool

### ISSUE THREAD

**Issue by nielsvaes** [nielsvaes/dcs_code_injector#9]
By the way, how do You reload whole Moose with the tool? I tried to copy-paste the Moose in the separate tab to drag it down to the buttons, but the tool have hung in paste action...

_Originally posted by @Amarok73 in https://github.com/nielsvaes/dcs_code_injector/issues/8#issuecomment-1844960334_

**Comment by nielsvaes** [comment]
This depends on how you load MOOSE in your mission. I do it like I show in this video here: https://www.youtube.com/watch?v=bIeg87Gfs1Y

So when I want to reload MOOSE, I just run `dofile(MOOSE_DYNAMIC_LOADER)` again.

**Comment by Amarok73** [comment]
If I'll use the "assert loadfile" method to reload the moose.lua file, the effect will be as expected, or this way there may be some issues?

**Comment by nielsvaes** [comment]
No, that should be exactly the same.
